{"nbformat":4,"nbformat_minor":0,"metadata":{"accelerator":"GPU","colab":{"name":"second_trainer_counting.ipynb","provenance":[],"collapsed_sections":[],"toc_visible":true,"machine_shape":"hm","mount_file_id":"1m8bh6G3ZCq_xCw17eY9wX8822yxrl-b_","authorship_tag":"ABX9TyO8ygGmAlIZ0ESyCJnCa5g5"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.3"}},"cells":[{"cell_type":"code","metadata":{"colab_type":"code","executionInfo":{"status":"ok","timestamp":1587738947986,"user_tz":-120,"elapsed":1703,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"id":"spDiWJ97I0vZ","outputId":"31296794-8bfd-4e3a-862f-76016fb577ef","colab":{"base_uri":"https://localhost:8080/","height":302}},"source":["# %cd ..\n","!nvidia-smi"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Fri Apr 24 14:35:51 2020       \n","+-----------------------------------------------------------------------------+\n","| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |\n","|-------------------------------+----------------------+----------------------+\n","| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n","| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n","|===============================+======================+======================|\n","|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |\n","| N/A   51C    P0    31W / 250W |      0MiB / 16280MiB |      0%      Default |\n","+-------------------------------+----------------------+----------------------+\n","                                                                               \n","+-----------------------------------------------------------------------------+\n","| Processes:                                                       GPU Memory |\n","|  GPU       PID   Type   Process name                             Usage      |\n","|=============================================================================|\n","|  No running processes found                                                 |\n","+-----------------------------------------------------------------------------+\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab_type":"code","id":"j5KSeQKwuZYB","outputId":"7fead6c0-f411-4951-8ed3-78465ddbdeb5","executionInfo":{"status":"ok","timestamp":1587739129526,"user_tz":-120,"elapsed":9671,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":894}},"source":["!pip install gdown\n","!pip install tensorflow-gpu --user\n","!pip install --upgrade keras"],"execution_count":9,"outputs":[{"output_type":"stream","text":["Requirement already satisfied: gdown in /usr/local/lib/python3.6/dist-packages (3.6.4)\n","Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from gdown) (2.21.0)\n","Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from gdown) (1.12.0)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from gdown) (4.38.0)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (2020.4.5.1)\n","Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (2.8)\n","Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (3.0.4)\n","Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->gdown) (1.24.3)\n","Requirement already satisfied: tensorflow-gpu in /root/.local/lib/python3.6/site-packages (2.1.0)\n","Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.12.0)\n","Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.1.0)\n","Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (3.10.0)\n","Requirement already satisfied: gast==0.2.2 in /root/.local/lib/python3.6/site-packages (from tensorflow-gpu) (0.2.2)\n","Requirement already satisfied: scipy==1.4.1; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.4.1)\n","Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.1.0)\n","Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.12.1)\n","Requirement already satisfied: wheel>=0.26; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.34.2)\n","Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in /root/.local/lib/python3.6/site-packages (from tensorflow-gpu) (2.1.1)\n","Requirement already satisfied: keras-applications>=1.0.8 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.0.8)\n","Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.8.1)\n","Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.18.2)\n","Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (1.28.1)\n","Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.2.0)\n","Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in /root/.local/lib/python3.6/site-packages (from tensorflow-gpu) (2.1.0)\n","Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (0.9.0)\n","Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu) (3.2.1)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf>=3.8.0->tensorflow-gpu) (46.1.3)\n","Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (0.4.1)\n","Requirement already satisfied: google-auth<2,>=1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.7.2)\n","Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.0.1)\n","Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (3.2.1)\n","Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (2.21.0)\n","Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.8->tensorflow-gpu) (2.10.0)\n","Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.3.0)\n","Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (0.2.8)\n","Requirement already satisfied: cachetools<3.2,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (3.1.1)\n","Requirement already satisfied: rsa<4.1,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (4.0)\n","Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (1.24.3)\n","Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (2.8)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (2020.4.5.1)\n","Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (3.0.4)\n","Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (3.1.0)\n","Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.6/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow-gpu) (0.4.8)\n","Requirement already up-to-date: keras in /usr/local/lib/python3.6/dist-packages (2.3.1)\n","Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from keras) (1.1.0)\n","Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras) (3.13)\n","Requirement already satisfied, skipping upgrade: h5py in /usr/local/lib/python3.6/dist-packages (from keras) (2.10.0)\n","Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /usr/local/lib/python3.6/dist-packages (from keras) (1.18.2)\n","Requirement already satisfied, skipping upgrade: scipy>=0.14 in /usr/local/lib/python3.6/dist-packages (from keras) (1.4.1)\n","Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from keras) (1.0.8)\n","Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from keras) (1.12.0)\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"33KexW3M7xhZ","colab_type":"code","outputId":"59aa685a-1c93-45c4-815b-30ab65394595","executionInfo":{"status":"ok","timestamp":1587739170635,"user_tz":-120,"elapsed":2491,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":252}},"source":["#quickfix error in callbacks of keras, pullrequest is already open in github\n","#later versions of tensorflow and keras should contain this fix\n","%cd ../../../../../../\n","from google.colab import files\n","import shutil\n","%cd root/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/\n","# files.download('callbacks.py')\n","!rm callbacks.py\n","shutil.copyfile('/content/drive/My Drive/person_detection/utils/callbacks.py', \n","                './callbacks.py')\n","!ls\n","\n"],"execution_count":12,"outputs":[{"output_type":"stream","text":["/\n","/root/.local/lib/python3.6/site-packages/tensorflow_core/python/keras\n","rm: cannot remove 'callbacks.py': No such file or directory\n","activations.py\t   estimator\t\t\t   optimizers.py\n","api\t\t   initializers.py\t\t   optimizer_v2\n","applications\t   __init__.py\t\t\t   premade\n","backend_config.py  keras_parameterized.py\t   preprocessing\n","backend.py\t   layers\t\t\t   __pycache__\n","callbacks.py\t   losses.py\t\t\t   regularizers.py\n","callbacks_v1.py    metrics.py\t\t\t   saving\n","constraints.py\t   mixed_precision\t\t   testing_utils.py\n","datasets\t   models.py\t\t\t   utils\n","distribute\t   model_subclassing_test_util.py  wrappers\n","engine\t\t   ops.py\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"J8LEtNbNn7Ri"},"source":["# Training\n","\n"]},{"cell_type":"code","metadata":{"colab_type":"code","id":"A-DO3mGwqq0i","colab":{}},"source":["from datetime import datetime\n","\n","logdir = '/content/drive/My\\ Drive/person_counting/tensorboard/colab_{}_trainer_nr_2/'.format(datetime.now().strftime(\"%Y-%m-%d-%H-%M-%S\"))\n","top_path = '/content/drive/My\\ Drive/person_detection/bus_videos/pcds_dataset_detected/'"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"do7gLVqi_jNB","colab_type":"code","outputId":"b9185a4c-71b8-4629-d75d-3e366709b009","executionInfo":{"status":"ok","timestamp":1587763003016,"user_tz":-120,"elapsed":526,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"colab":{"base_uri":"https://localhost:8080/","height":34}},"source":["%cd /content/drive/My\\ Drive/"],"execution_count":22,"outputs":[{"output_type":"stream","text":["/content/drive/My Drive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"E8ep37lYAEkX","colab_type":"code","outputId":"6ef389ce-642b-4076-9d31-b745350328fe","colab":{"base_uri":"https://localhost:8080/","height":0}},"source":["!python -m person_counting.models.cnn_regression --topdir-log {logdir} \\\n","                                                 --n-runs 100 \\\n","                                                 --top-path {top_path}\\\n","                                                 --batch-size 8\\\n","                                                 --filter-rows-factor 1\n","                                                 \n","                                                 "],"execution_count":0,"outputs":[{"output_type":"stream","text":["Using TensorFlow backend.\n","2020-04-24 21:19:42.851670: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2020-04-24 21:19:42.851789: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2020-04-24 21:19:42.851809: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n","Dataset contains: \n","0 training csvs \n","0 testing csvs\n","[1.57445582e-04 3.17561051e-02 4.23590071e-03 1.24052049e-03\n"," 2.10399433e-05 2.10352698e-05 8.53698372e-06 1.45772159e-02\n"," 1.26890775e-03 3.39828905e-03]\n","2020-04-24 21:19:44.777407: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-04-24 21:19:44.793493: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.794384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-04-24 21:19:44.794760: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-04-24 21:19:44.797616: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-04-24 21:19:44.801049: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-04-24 21:19:44.801607: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-04-24 21:19:44.805353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-04-24 21:19:44.806618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-04-24 21:19:44.812659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-04-24 21:19:44.812798: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.813892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.814735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0\n","2020-04-24 21:19:44.815119: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-04-24 21:19:44.820179: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz\n","2020-04-24 21:19:44.820628: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27b44c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-04-24 21:19:44.820671: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-04-24 21:19:44.915749: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.916923: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27b4d80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-04-24 21:19:44.917021: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-04-24 21:19:44.917319: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.918201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-04-24 21:19:44.918273: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-04-24 21:19:44.918304: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-04-24 21:19:44.918345: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-04-24 21:19:44.918380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-04-24 21:19:44.918411: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-04-24 21:19:44.918437: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-04-24 21:19:44.918464: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-04-24 21:19:44.918564: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.919548: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.920456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0\n","2020-04-24 21:19:44.920522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-04-24 21:19:44.922349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-04-24 21:19:44.922383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 \n","2020-04-24 21:19:44.922392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N \n","2020-04-24 21:19:44.922619: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.923672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-24 21:19:44.924616: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-04-24 21:19:44.924671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15216 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Tried to create a MaxPool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Model: \"sequential_1\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_1 (Conv2D)            (None, 524, 64, 3)        150       \n","_________________________________________________________________\n","max_pooling2d_1 (MaxPooling2 (None, 131, 16, 3)        0         \n","_________________________________________________________________\n","batch_normalization_1 (Batch (None, 131, 16, 3)        12        \n","_________________________________________________________________\n","conv2d_2 (Conv2D)            (None, 125, 10, 3)        444       \n","_________________________________________________________________\n","max_pooling2d_2 (MaxPooling2 (None, 31, 2, 3)          0         \n","_________________________________________________________________\n","batch_normalization_2 (Batch (None, 31, 2, 3)          12        \n","_________________________________________________________________\n","flatten_1 (Flatten)          (None, 186)               0         \n","_________________________________________________________________\n","dense_1 (Dense)              (None, 1)                 187       \n","=================================================================\n","Total params: 805\n","Trainable params: 793\n","Non-trainable params: 12\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  Adam\n","max_pool_size :  4\n","learning_rate :  1.3885067726533708e-05\n","layer_number :  3\n","kernel_size :  7\n","kernel_number :  3\n","batch_normalization :  True\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","2020-04-24 21:19:54.208467: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-04-24 21:19:54.487658: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","92/92 [==============================] - 32s 344ms/step - loss: 0.3696 - val_loss: 0.2121\n","Epoch 2/12\n","92/92 [==============================] - 25s 273ms/step - loss: 0.3035 - val_loss: 0.2117\n","Epoch 3/12\n","92/92 [==============================] - 27s 288ms/step - loss: 0.2717 - val_loss: 0.2054\n","Epoch 4/12\n","92/92 [==============================] - 24s 265ms/step - loss: 0.2051 - val_loss: 0.1603\n","Epoch 5/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.2260 - val_loss: 0.2061\n","Epoch 6/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.1847 - val_loss: 0.1037\n","Epoch 7/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.1353 - val_loss: 0.1118\n","Epoch 8/12\n","92/92 [==============================] - 27s 292ms/step - loss: 0.1699 - val_loss: 0.1793\n","Epoch 9/12\n","92/92 [==============================] - 27s 293ms/step - loss: 0.1648 - val_loss: 0.1077\n","Epoch 10/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.1518 - val_loss: 0.1170\n","Epoch 11/12\n","92/92 [==============================] - 26s 284ms/step - loss: 0.0979 - val_loss: 0.0739\n","Epoch 12/12\n","92/92 [==============================] - 25s 267ms/step - loss: 0.1170 - val_loss: 0.1304\n","Tried to create a MaxPool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Model: \"sequential_2\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_4 (Conv2D)            (None, 263, 66, 5)        130       \n","_________________________________________________________________\n","max_pooling2d_3 (MaxPooling2 (None, 65, 16, 5)         0         \n","_________________________________________________________________\n","batch_normalization_3 (Batch (None, 65, 16, 5)         20        \n","_________________________________________________________________\n","conv2d_5 (Conv2D)            (None, 31, 12, 5)         630       \n","_________________________________________________________________\n","max_pooling2d_4 (MaxPooling2 (None, 7, 3, 5)           0         \n","_________________________________________________________________\n","batch_normalization_4 (Batch (None, 7, 3, 5)           20        \n","_________________________________________________________________\n","flatten_2 (Flatten)          (None, 105)               0         \n","_________________________________________________________________\n","dense_2 (Dense)              (None, 1)                 106       \n","=================================================================\n","Total params: 906\n","Trainable params: 886\n","Non-trainable params: 20\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  Adam\n","max_pool_size :  4\n","learning_rate :  0.00810540331268768\n","layer_number :  3\n","kernel_size :  5\n","kernel_number :  5\n","batch_normalization :  True\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 30s 329ms/step - loss: 0.0084 - val_loss: 0.0023\n","Epoch 2/12\n","92/92 [==============================] - 27s 289ms/step - loss: 0.0019 - val_loss: 0.0012\n","Epoch 3/12\n","92/92 [==============================] - 23s 251ms/step - loss: 0.0016 - val_loss: 0.0017\n","Epoch 4/12\n","92/92 [==============================] - 27s 298ms/step - loss: 8.8384e-04 - val_loss: 0.0019\n","Epoch 5/12\n","92/92 [==============================] - 27s 292ms/step - loss: 5.5282e-04 - val_loss: 0.0011\n","Epoch 6/12\n","92/92 [==============================] - 26s 281ms/step - loss: 0.0013 - val_loss: 0.0019\n","Epoch 7/12\n","92/92 [==============================] - 27s 296ms/step - loss: 6.7294e-04 - val_loss: 5.1336e-04\n","Epoch 8/12\n","92/92 [==============================] - 28s 307ms/step - loss: 6.5972e-04 - val_loss: 0.0013\n","Epoch 9/12\n","92/92 [==============================] - 26s 278ms/step - loss: 5.4514e-04 - val_loss: 0.0030\n","Epoch 10/12\n","92/92 [==============================] - 27s 293ms/step - loss: 5.9839e-04 - val_loss: 0.0017\n","Epoch 11/12\n","92/92 [==============================] - 26s 286ms/step - loss: 2.8580e-04 - val_loss: 6.1396e-05\n","Epoch 12/12\n","92/92 [==============================] - 25s 274ms/step - loss: 3.5383e-04 - val_loss: 1.7738e-04\n","Tried to create a MaxPool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Model: \"sequential_3\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_7 (Conv2D)            (None, 262, 64, 3)        150       \n","_________________________________________________________________\n","max_pooling2d_5 (MaxPooling2 (None, 87, 21, 3)         0         \n","_________________________________________________________________\n","conv2d_8 (Conv2D)            (None, 41, 15, 3)         444       \n","_________________________________________________________________\n","max_pooling2d_6 (MaxPooling2 (None, 13, 5, 3)          0         \n","_________________________________________________________________\n","flatten_3 (Flatten)          (None, 195)               0         \n","_________________________________________________________________\n","dense_3 (Dense)              (None, 1)                 196       \n","=================================================================\n","Total params: 790\n","Trainable params: 790\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  Adam\n","max_pool_size :  3\n","learning_rate :  6.520202557320308e-05\n","layer_number :  3\n","kernel_size :  7\n","kernel_number :  3\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 30s 325ms/step - loss: 0.2106 - val_loss: 0.1894\n","Epoch 2/12\n","92/92 [==============================] - 24s 263ms/step - loss: 0.1775 - val_loss: 0.1543\n","Epoch 3/12\n","92/92 [==============================] - 24s 264ms/step - loss: 0.1172 - val_loss: 0.0906\n","Epoch 4/12\n","92/92 [==============================] - 27s 295ms/step - loss: 0.0572 - val_loss: 0.0478\n","Epoch 5/12\n","92/92 [==============================] - 28s 300ms/step - loss: 0.0299 - val_loss: 0.0157\n","Epoch 6/12\n","92/92 [==============================] - 27s 294ms/step - loss: 0.0138 - val_loss: 0.0089\n","Epoch 7/12\n","92/92 [==============================] - 26s 287ms/step - loss: 0.0066 - val_loss: 0.0065\n","Epoch 8/12\n","92/92 [==============================] - 29s 313ms/step - loss: 0.0037 - val_loss: 0.0029\n","Epoch 9/12\n","92/92 [==============================] - 25s 271ms/step - loss: 0.0037 - val_loss: 0.0015\n","Epoch 10/12\n","92/92 [==============================] - 27s 298ms/step - loss: 0.0023 - val_loss: 0.0020\n","Epoch 11/12\n","92/92 [==============================] - 28s 301ms/step - loss: 0.0023 - val_loss: 0.0023\n","Epoch 12/12\n","92/92 [==============================] - 24s 261ms/step - loss: 0.0020 - val_loss: 0.0011\n","Model: \"sequential_4\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_10 (Conv2D)           (None, 262, 63, 7)        455       \n","_________________________________________________________________\n","max_pooling2d_7 (MaxPooling2 (None, 65, 15, 7)         0         \n","_________________________________________________________________\n","batch_normalization_5 (Batch (None, 65, 15, 7)         28        \n","_________________________________________________________________\n","conv2d_11 (Conv2D)           (None, 29, 8, 7)          3143      \n","_________________________________________________________________\n","max_pooling2d_8 (MaxPooling2 (None, 7, 2, 7)           0         \n","_________________________________________________________________\n","flatten_4 (Flatten)          (None, 98)                0         \n","_________________________________________________________________\n","dense_4 (Dense)              (None, 1)                 99        \n","=================================================================\n","Total params: 3,725\n","Trainable params: 3,711\n","Non-trainable params: 14\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  Adam\n","max_pool_size :  4\n","learning_rate :  0.00016201304634928993\n","layer_number :  2\n","kernel_size :  8\n","kernel_number :  7\n","batch_normalization :  True\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 30s 331ms/step - loss: 0.1746 - val_loss: 0.1681\n","Epoch 2/12\n","92/92 [==============================] - 26s 283ms/step - loss: 0.0138 - val_loss: 0.1130\n","Epoch 3/12\n","92/92 [==============================] - 24s 264ms/step - loss: 0.0040 - val_loss: 0.0543\n","Epoch 4/12\n","92/92 [==============================] - 26s 280ms/step - loss: 0.0045 - val_loss: 0.0272\n","Epoch 5/12\n","92/92 [==============================] - 27s 292ms/step - loss: 0.0032 - val_loss: 0.0133\n","Epoch 6/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.0099 - val_loss: 0.0034\n","Epoch 7/12\n","92/92 [==============================] - 26s 286ms/step - loss: 0.0200 - val_loss: 0.0767\n","Epoch 8/12\n","92/92 [==============================] - 27s 295ms/step - loss: 0.0023 - val_loss: 0.0029\n","Epoch 9/12\n","92/92 [==============================] - 25s 267ms/step - loss: 0.0031 - val_loss: 0.0016\n","Epoch 10/12\n","92/92 [==============================] - 28s 303ms/step - loss: 0.0024 - val_loss: 0.0020\n","Epoch 11/12\n","92/92 [==============================] - 27s 292ms/step - loss: 0.0195 - val_loss: 6.4069e-04\n","Epoch 12/12\n","92/92 [==============================] - 24s 265ms/step - loss: 0.0019 - val_loss: 0.0021\n","Model: \"sequential_5\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_12 (Conv2D)           (None, 527, 67, 9)        153       \n","_________________________________________________________________\n","max_pooling2d_9 (MaxPooling2 (None, 131, 16, 9)        0         \n","_________________________________________________________________\n","conv2d_13 (Conv2D)           (None, 128, 13, 9)        1305      \n","_________________________________________________________________\n","max_pooling2d_10 (MaxPooling (None, 32, 3, 9)          0         \n","_________________________________________________________________\n","flatten_5 (Flatten)          (None, 864)               0         \n","_________________________________________________________________\n","dense_5 (Dense)              (None, 1)                 865       \n","=================================================================\n","Total params: 2,323\n","Trainable params: 2,323\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  Adam\n","max_pool_size :  4\n","learning_rate :  0.0021051848318983713\n","layer_number :  2\n","kernel_size :  4\n","kernel_number :  9\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 33s 356ms/step - loss: 0.0189 - val_loss: 0.0036\n","Epoch 2/12\n","92/92 [==============================] - 23s 252ms/step - loss: 0.0022 - val_loss: 0.0024\n","Epoch 3/12\n","92/92 [==============================] - 26s 278ms/step - loss: 0.0018 - val_loss: 0.0035\n","Epoch 4/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.0020 - val_loss: 0.0017\n","Epoch 5/12\n","92/92 [==============================] - 26s 288ms/step - loss: 0.0024 - val_loss: 0.0042\n","Epoch 6/12\n","92/92 [==============================] - 26s 284ms/step - loss: 0.0024 - val_loss: 0.0013\n","Epoch 7/12\n","92/92 [==============================] - 24s 263ms/step - loss: 0.0015 - val_loss: 0.0014\n","Epoch 8/12\n","92/92 [==============================] - 25s 275ms/step - loss: 7.1144e-04 - val_loss: 7.7123e-04\n","Epoch 9/12\n","92/92 [==============================] - 25s 276ms/step - loss: 1.3502e-04 - val_loss: 3.5208e-04\n","Epoch 10/12\n","92/92 [==============================] - 25s 276ms/step - loss: 3.2628e-04 - val_loss: 3.1390e-04\n","Epoch 11/12\n","92/92 [==============================] - 28s 309ms/step - loss: 2.0601e-04 - val_loss: 1.9736e-04\n","Epoch 12/12\n","92/92 [==============================] - 26s 283ms/step - loss: 1.6490e-04 - val_loss: 7.8907e-04\n","Model: \"sequential_6\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_14 (Conv2D)           (None, 264, 67, 8)        136       \n","_________________________________________________________________\n","max_pooling2d_11 (MaxPooling (None, 66, 16, 8)         0         \n","_________________________________________________________________\n","conv2d_15 (Conv2D)           (None, 32, 13, 8)         1032      \n","_________________________________________________________________\n","max_pooling2d_12 (MaxPooling (None, 8, 3, 8)           0         \n","_________________________________________________________________\n","flatten_6 (Flatten)          (None, 192)               0         \n","_________________________________________________________________\n","dense_6 (Dense)              (None, 1)                 193       \n","=================================================================\n","Total params: 1,361\n","Trainable params: 1,361\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  RMSProp\n","max_pool_size :  4\n","learning_rate :  0.003866191056649883\n","layer_number :  2\n","kernel_size :  4\n","kernel_number :  8\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 31s 335ms/step - loss: 0.0057 - val_loss: 2.3419e-04\n","Epoch 2/12\n","92/92 [==============================] - 25s 267ms/step - loss: 3.4332e-04 - val_loss: 1.6551e-04\n","Epoch 3/12\n","92/92 [==============================] - 24s 260ms/step - loss: 3.7087e-04 - val_loss: 9.8381e-04\n","Epoch 4/12\n","92/92 [==============================] - 27s 288ms/step - loss: 2.7910e-04 - val_loss: 0.0011\n","Epoch 5/12\n","92/92 [==============================] - 27s 293ms/step - loss: 3.0336e-04 - val_loss: 2.1910e-04\n","Epoch 6/12\n","92/92 [==============================] - 27s 291ms/step - loss: 2.7704e-04 - val_loss: 2.1581e-04\n","Epoch 7/12\n","92/92 [==============================] - 26s 283ms/step - loss: 2.9573e-04 - val_loss: 3.8644e-04\n","Epoch 8/12\n","92/92 [==============================] - 28s 309ms/step - loss: 2.6105e-04 - val_loss: 1.7384e-04\n","Epoch 9/12\n","92/92 [==============================] - 26s 286ms/step - loss: 2.5710e-04 - val_loss: 8.6144e-04\n","Epoch 10/12\n","92/92 [==============================] - 26s 278ms/step - loss: 2.4916e-04 - val_loss: 7.1180e-04\n","Epoch 11/12\n","92/92 [==============================] - 27s 295ms/step - loss: 2.1855e-04 - val_loss: 0.0013\n","Epoch 12/12\n","92/92 [==============================] - 25s 272ms/step - loss: 1.5496e-04 - val_loss: 1.4516e-04\n","Model: \"sequential_7\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_16 (Conv2D)           (None, 523, 63, 7)        455       \n","_________________________________________________________________\n","max_pooling2d_13 (MaxPooling (None, 130, 15, 7)        0         \n","_________________________________________________________________\n","conv2d_17 (Conv2D)           (None, 123, 8, 7)         3143      \n","_________________________________________________________________\n","max_pooling2d_14 (MaxPooling (None, 30, 2, 7)          0         \n","_________________________________________________________________\n","flatten_7 (Flatten)          (None, 420)               0         \n","_________________________________________________________________\n","dense_7 (Dense)              (None, 1)                 421       \n","=================================================================\n","Total params: 4,019\n","Trainable params: 4,019\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  RMSProp\n","max_pool_size :  4\n","learning_rate :  0.007678363732329449\n","layer_number :  2\n","kernel_size :  8\n","kernel_number :  7\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 31s 334ms/step - loss: 0.0047 - val_loss: 0.0022\n","Epoch 2/12\n","92/92 [==============================] - 24s 266ms/step - loss: 0.0019 - val_loss: 0.0019\n","Epoch 3/12\n","92/92 [==============================] - 26s 286ms/step - loss: 0.0102 - val_loss: 0.0015\n","Epoch 4/12\n","92/92 [==============================] - 26s 281ms/step - loss: 0.0026 - val_loss: 0.0021\n","Epoch 5/12\n","92/92 [==============================] - 26s 281ms/step - loss: 0.0041 - val_loss: 0.0023\n","Epoch 6/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.0124 - val_loss: 0.0024\n","Epoch 7/12\n","92/92 [==============================] - 25s 277ms/step - loss: 0.0018 - val_loss: 0.0034\n","Epoch 8/12\n","92/92 [==============================] - 29s 310ms/step - loss: 0.0023 - val_loss: 0.0032\n","Epoch 9/12\n","92/92 [==============================] - 26s 280ms/step - loss: 0.0066 - val_loss: 0.0040\n","Epoch 10/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.0022 - val_loss: 0.0025\n","Epoch 11/12\n","92/92 [==============================] - 28s 306ms/step - loss: 7.0884e-04 - val_loss: 2.2930e-04\n","Epoch 12/12\n","92/92 [==============================] - 24s 261ms/step - loss: 0.0011 - val_loss: 0.0020\n","Model: \"sequential_8\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_18 (Conv2D)           (None, 262, 63, 5)        325       \n","_________________________________________________________________\n","max_pooling2d_15 (MaxPooling (None, 131, 31, 5)        0         \n","_________________________________________________________________\n","conv2d_19 (Conv2D)           (None, 62, 24, 5)         1605      \n","_________________________________________________________________\n","max_pooling2d_16 (MaxPooling (None, 31, 12, 5)         0         \n","_________________________________________________________________\n","flatten_8 (Flatten)          (None, 1860)              0         \n","_________________________________________________________________\n","dense_8 (Dense)              (None, 1)                 1861      \n","=================================================================\n","Total params: 3,791\n","Trainable params: 3,791\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  Adam\n","max_pool_size :  2\n","learning_rate :  7.803532954683548e-05\n","layer_number :  2\n","kernel_size :  8\n","kernel_number :  5\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 34s 367ms/step - loss: 0.1776 - val_loss: 0.0809\n","Epoch 2/12\n","92/92 [==============================] - 24s 263ms/step - loss: 0.0275 - val_loss: 0.0047\n","Epoch 3/12\n","92/92 [==============================] - 23s 253ms/step - loss: 0.0027 - val_loss: 0.0011\n","Epoch 4/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.0016 - val_loss: 0.0011\n","Epoch 5/12\n","92/92 [==============================] - 26s 281ms/step - loss: 0.0013 - val_loss: 0.0011\n","Epoch 6/12\n","92/92 [==============================] - 27s 289ms/step - loss: 0.0019 - val_loss: 0.0014\n","Epoch 7/12\n","92/92 [==============================] - 26s 279ms/step - loss: 0.0014 - val_loss: 6.2057e-04\n","Epoch 8/12\n","92/92 [==============================] - 27s 289ms/step - loss: 0.0016 - val_loss: 0.0026\n","Epoch 9/12\n","92/92 [==============================] - 26s 284ms/step - loss: 0.0015 - val_loss: 0.0017\n","Epoch 10/12\n","92/92 [==============================] - 28s 299ms/step - loss: 0.0016 - val_loss: 0.0023\n","Epoch 11/12\n","92/92 [==============================] - 28s 305ms/step - loss: 9.1133e-04 - val_loss: 0.0024\n","Epoch 12/12\n","92/92 [==============================] - 25s 273ms/step - loss: 8.3118e-04 - val_loss: 6.1887e-04\n","Tried to create a MaxPool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Model: \"sequential_9\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_20 (Conv2D)           (None, 524, 64, 4)        200       \n","_________________________________________________________________\n","max_pooling2d_17 (MaxPooling (None, 131, 16, 4)        0         \n","_________________________________________________________________\n","conv2d_21 (Conv2D)           (None, 125, 10, 4)        788       \n","_________________________________________________________________\n","max_pooling2d_18 (MaxPooling (None, 31, 2, 4)          0         \n","_________________________________________________________________\n","flatten_9 (Flatten)          (None, 248)               0         \n","_________________________________________________________________\n","dense_9 (Dense)              (None, 1)                 249       \n","=================================================================\n","Total params: 1,237\n","Trainable params: 1,237\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  Adam\n","max_pool_size :  4\n","learning_rate :  2.2708853184312736e-05\n","layer_number :  3\n","kernel_size :  7\n","kernel_number :  4\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 32s 342ms/step - loss: 0.2442 - val_loss: 0.2301\n","Epoch 2/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.2317 - val_loss: 0.2325\n","Epoch 3/12\n","92/92 [==============================] - 25s 272ms/step - loss: 0.2166 - val_loss: 0.2073\n","Epoch 4/12\n","92/92 [==============================] - 27s 293ms/step - loss: 0.2017 - val_loss: 0.1928\n","Epoch 5/12\n","92/92 [==============================] - 26s 287ms/step - loss: 0.1825 - val_loss: 0.1721\n","Epoch 6/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.1547 - val_loss: 0.1355\n","Epoch 7/12\n","92/92 [==============================] - 25s 276ms/step - loss: 0.1353 - val_loss: 0.1332\n","Epoch 8/12\n","92/92 [==============================] - 26s 283ms/step - loss: 0.1032 - val_loss: 0.1029\n","Epoch 9/12\n","92/92 [==============================] - 30s 326ms/step - loss: 0.0736 - val_loss: 0.0593\n","Epoch 10/12\n","92/92 [==============================] - 24s 263ms/step - loss: 0.0528 - val_loss: 0.0268\n","Epoch 11/12\n","92/92 [==============================] - 27s 296ms/step - loss: 0.0421 - val_loss: 0.0265\n","Epoch 12/12\n","92/92 [==============================] - 26s 286ms/step - loss: 0.0270 - val_loss: 0.0205\n","Model: \"sequential_10\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_23 (Conv2D)           (None, 263, 66, 7)        182       \n","_________________________________________________________________\n","max_pooling2d_19 (MaxPooling (None, 131, 33, 7)        0         \n","_________________________________________________________________\n","conv2d_24 (Conv2D)           (None, 64, 29, 7)         1232      \n","_________________________________________________________________\n","max_pooling2d_20 (MaxPooling (None, 32, 14, 7)         0         \n","_________________________________________________________________\n","conv2d_25 (Conv2D)           (None, 14, 10, 7)         1232      \n","_________________________________________________________________\n","max_pooling2d_21 (MaxPooling (None, 7, 5, 7)           0         \n","_________________________________________________________________\n","flatten_10 (Flatten)         (None, 245)               0         \n","_________________________________________________________________\n","dense_10 (Dense)             (None, 1)                 246       \n","=================================================================\n","Total params: 2,892\n","Trainable params: 2,892\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  Adam\n","max_pool_size :  2\n","learning_rate :  0.002231516592287135\n","layer_number :  3\n","kernel_size :  5\n","kernel_number :  7\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 32s 349ms/step - loss: 0.0190 - val_loss: 0.0031\n","Epoch 2/12\n","92/92 [==============================] - 25s 275ms/step - loss: 0.0018 - val_loss: 0.0027\n","Epoch 3/12\n","92/92 [==============================] - 26s 284ms/step - loss: 0.0021 - val_loss: 0.0021\n","Epoch 4/12\n","92/92 [==============================] - 26s 278ms/step - loss: 0.0020 - val_loss: 0.0023\n","Epoch 5/12\n","92/92 [==============================] - 26s 280ms/step - loss: 0.0021 - val_loss: 0.0025\n","Epoch 6/12\n","92/92 [==============================] - 27s 297ms/step - loss: 0.0026 - val_loss: 0.0021\n","Epoch 7/12\n","92/92 [==============================] - 26s 287ms/step - loss: 0.0020 - val_loss: 0.0025\n","Epoch 8/12\n","92/92 [==============================] - 26s 281ms/step - loss: 0.0021 - val_loss: 0.0025\n","Epoch 9/12\n","92/92 [==============================] - 29s 316ms/step - loss: 0.0024 - val_loss: 0.0022\n","Epoch 10/12\n","92/92 [==============================] - 27s 295ms/step - loss: 0.0021 - val_loss: 0.0022\n","Epoch 11/12\n","92/92 [==============================] - 26s 287ms/step - loss: 0.0019 - val_loss: 0.0021\n","Epoch 12/12\n","92/92 [==============================] - 26s 286ms/step - loss: 0.0023 - val_loss: 0.0014\n","Tried to create a MaxPool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Model: \"sequential_11\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_26 (Conv2D)           (None, 526, 66, 7)        182       \n","_________________________________________________________________\n","max_pooling2d_22 (MaxPooling (None, 131, 16, 7)        0         \n","_________________________________________________________________\n","conv2d_27 (Conv2D)           (None, 127, 12, 7)        1232      \n","_________________________________________________________________\n","max_pooling2d_23 (MaxPooling (None, 31, 3, 7)          0         \n","_________________________________________________________________\n","flatten_11 (Flatten)         (None, 651)               0         \n","_________________________________________________________________\n","dense_11 (Dense)             (None, 1)                 652       \n","=================================================================\n","Total params: 2,066\n","Trainable params: 2,066\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  Adam\n","max_pool_size :  4\n","learning_rate :  0.007228663045101136\n","layer_number :  3\n","kernel_size :  5\n","kernel_number :  7\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 31s 333ms/step - loss: 0.0067 - val_loss: 0.0040\n","Epoch 2/12\n","92/92 [==============================] - 25s 273ms/step - loss: 0.0017 - val_loss: 0.0014\n","Epoch 3/12\n","92/92 [==============================] - 25s 271ms/step - loss: 0.0019 - val_loss: 0.0023\n","Epoch 4/12\n","92/92 [==============================] - 28s 308ms/step - loss: 0.0022 - val_loss: 0.0039\n","Epoch 5/12\n","92/92 [==============================] - 27s 293ms/step - loss: 0.0022 - val_loss: 0.0025\n","Epoch 6/12\n","92/92 [==============================] - 26s 288ms/step - loss: 0.0026 - val_loss: 0.0021\n","Epoch 7/12\n","92/92 [==============================] - 25s 267ms/step - loss: 0.0020 - val_loss: 0.0036\n","Epoch 8/12\n","92/92 [==============================] - 26s 279ms/step - loss: 0.0021 - val_loss: 0.0038\n","Epoch 9/12\n","92/92 [==============================] - 29s 321ms/step - loss: 0.0024 - val_loss: 0.0019\n","Epoch 10/12\n","92/92 [==============================] - 25s 277ms/step - loss: 0.0023 - val_loss: 0.0032\n","Epoch 11/12\n","92/92 [==============================] - 27s 293ms/step - loss: 0.0023 - val_loss: 0.0039\n","Epoch 12/12\n","92/92 [==============================] - 28s 302ms/step - loss: 0.0014 - val_loss: 0.0017\n","Model: \"sequential_12\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_29 (Conv2D)           (None, 522, 62, 5)        410       \n","_________________________________________________________________\n","max_pooling2d_24 (MaxPooling (None, 130, 15, 5)        0         \n","_________________________________________________________________\n","batch_normalization_6 (Batch (None, 130, 15, 5)        20        \n","_________________________________________________________________\n","conv2d_30 (Conv2D)           (None, 122, 7, 5)         2030      \n","_________________________________________________________________\n","max_pooling2d_25 (MaxPooling (None, 30, 1, 5)          0         \n","_________________________________________________________________\n","flatten_12 (Flatten)         (None, 150)               0         \n","_________________________________________________________________\n","dense_12 (Dense)             (None, 1)                 151       \n","=================================================================\n","Total params: 2,611\n","Trainable params: 2,601\n","Non-trainable params: 10\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  RMSProp\n","max_pool_size :  4\n","learning_rate :  0.0006413377163067407\n","layer_number :  2\n","kernel_size :  9\n","kernel_number :  5\n","batch_normalization :  True\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","30/92 [========>.....................] - ETA: 24s - loss: 0.02082020-04-24 22:19:30.821421: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:31.752728: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:31.940331: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.042469: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.192805: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.296001: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.525814: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.541435: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.624533: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.633100: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.634093: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.684563: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.721530: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.792557: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.813697: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:19:32.869454: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py:718: UserWarning: An input could not be retrieved. It could be because a worker has died.We do not have any information on the lost sample.\n","  UserWarning)\n","2020-04-24 22:25:00.200771: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:00.204359: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","41/92 [============>.................] - ETA: 10:11 - loss: 0.01582020-04-24 22:27:31.947225: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.019439: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.121748: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.168319: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.280549: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.404000: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.416882: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.436932: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.441048: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.493568: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:27:32.498679: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","45/92 [=============>................] - ETA: 9:05 - loss: 0.0145 2020-04-24 22:28:00.707137: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:28:00.711197: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:28:00.719167: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","48/92 [==============>...............] - ETA: 8:26 - loss: 0.01362020-04-24 22:28:30.474336: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","49/92 [==============>...............] - ETA: 12:27 - loss: 0.01342020-04-24 22:33:30.579838: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","50/92 [===============>..............] - ETA: 13:11 - loss: 0.01312020-04-24 22:35:00.592619: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","60/92 [==================>...........] - ETA: 8:54 - loss: 0.0110 2020-04-24 22:36:01.997309: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.316135: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.361609: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.414083: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.435720: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.466528: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.498681: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.538794: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.629226: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.633285: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:02.670600: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","62/92 [===================>..........] - ETA: 8:19 - loss: 0.01072020-04-24 22:36:30.993803: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:30.993757: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:36:31.013162: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","65/92 [====================>.........] - ETA: 7:21 - loss: 0.01022020-04-24 22:37:00.803327: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","66/92 [====================>.........] - ETA: 8:56 - loss: 0.01002020-04-24 22:42:00.808487: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","67/92 [====================>.........] - ETA: 9:01 - loss: 0.00992020-04-24 22:43:30.840077: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","76/92 [=======================>......] - ETA: 5:18 - loss: 0.00872020-04-24 22:44:32.403426: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.421647: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.433558: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.701977: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.721833: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.775708: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.817434: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.844895: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.881892: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.908587: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:44:32.909557: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","79/92 [========================>.....] - ETA: 4:13 - loss: 0.00842020-04-24 22:45:01.311518: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:45:01.317849: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:45:01.344791: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","82/92 [=========================>....] - ETA: 3:11 - loss: 0.00812020-04-24 22:45:31.096797: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","83/92 [==========================>...] - ETA: 3:23 - loss: 0.00802020-04-24 22:50:31.097355: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","84/92 [==========================>...] - ETA: 3:06 - loss: 0.00792020-04-24 22:52:01.134082: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","90/92 [============================>.] - ETA: 44s - loss: 0.0074 2020-04-24 22:53:03.355120: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:03.819646: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:04.051045: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:04.229187: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:04.274566: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:04.411412: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:04.446440: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:04.916118: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:04.927342: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","92/92 [==============================] - 2028s 22s/step - loss: 0.0072 - val_loss: 0.1078\n","Epoch 2/12\n"," 3/92 [..............................] - ETA: 2s - loss: 5.4132e-062020-04-24 22:53:06.780381: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:07.406465: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:07.488741: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.149934: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.244209: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.523816: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.676876: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.796650: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.813091: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.824279: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:08.839311: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:09.093637: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:09.107768: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:09.116575: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:09.196489: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:09.284724: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:09.286061: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n"," 4/92 [>.............................] - ETA: 11:02 - loss: 6.3659e-062020-04-24 22:53:37.038915: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:37.063015: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:53:37.076708: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n"," 7/92 [=>............................] - ETA: 12:10 - loss: 3.2106e-052020-04-24 22:54:06.823934: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:54:06.823934: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:54:36.811653: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:55:06.793125: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:55:36.785729: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:56:06.771509: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:56:36.778253: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:57:06.761627: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:57:36.713461: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:58:06.790235: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:58:36.805023: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n"," 8/92 [=>............................] - ETA: 1:03:02 - loss: 2.9666e-052020-04-24 22:59:06.786722: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:59:06.845808: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 22:59:36.852514: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:00:06.822453: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n"," 9/92 [=>............................] - ETA: 1:09:11 - loss: 3.1077e-052020-04-24 23:00:36.857002: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:00:36.878483: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:01:06.836749: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:01:36.868580: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:02:06.834294: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:02:36.868034: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:03:06.851798: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:03:36.850216: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:04:06.835519: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:04:36.852845: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:05:06.838041: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:05:36.843342: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:06:06.841083: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:06:36.853802: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:07:06.845346: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:07:36.838113: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:08:06.845719: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:08:36.847744: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:09:06.846698: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:09:36.852160: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:10:06.862247: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:10:36.857278: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:11:06.842009: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:11:36.858031: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:12:06.859558: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:12:36.866907: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:13:06.872390: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:13:36.869341: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:14:06.853648: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:14:36.873268: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:15:06.859607: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:15:36.890012: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:16:06.864827: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:16:36.874411: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:17:06.850462: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:17:36.877590: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:18:06.868077: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:18:36.872804: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:19:06.865914: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:19:36.851581: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:20:06.872784: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:20:36.879129: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:21:06.861823: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:21:36.850962: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:22:06.856509: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:22:36.870051: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:23:06.870494: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:23:36.863192: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:24:06.868652: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:24:36.862291: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:25:06.848187: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:25:36.839693: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:26:06.810490: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:26:36.816691: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:27:06.807761: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:27:36.829612: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:28:07.123641: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:28:36.816297: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:29:06.796284: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:29:36.792929: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:30:06.783435: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:30:36.764558: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:31:06.773070: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:31:36.766405: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:32:06.766791: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:32:36.773238: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:33:06.740201: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:33:36.748986: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:34:06.725067: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:34:36.723462: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:35:06.716062: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:35:36.709818: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","91/92 [============================>.] - ETA: 34s - loss: 0.0015 2020-04-24 23:44:53.675734: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:44:55.061556: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:45:22.440812: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:45:52.433785: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:46:22.436444: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:46:52.450160: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:47:22.458674: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:47:52.456049: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:48:22.468213: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:48:52.441893: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:49:22.447285: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:49:52.443575: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:50:22.170481: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:50:22.490525: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:50:52.457562: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","2020-04-24 23:51:22.405271: F tensorflow/stream_executor/cuda/cuda_driver.cc:257] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error\n","92/92 [==============================] - 4039s 44s/step - loss: 0.0015 - val_loss: 0.0965\n","Epoch 3/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.0011 - val_loss: 0.0438\n","Epoch 4/12\n","92/92 [==============================] - 25s 273ms/step - loss: 0.0026 - val_loss: 0.0033\n","Epoch 5/12\n","92/92 [==============================] - 26s 281ms/step - loss: 0.0010 - val_loss: 0.0018\n","Epoch 6/12\n","92/92 [==============================] - 28s 309ms/step - loss: 6.0255e-04 - val_loss: 0.0047\n","Epoch 7/12\n","92/92 [==============================] - 26s 280ms/step - loss: 5.2827e-04 - val_loss: 3.8231e-04\n","Epoch 8/12\n","92/92 [==============================] - 25s 268ms/step - loss: 0.0027 - val_loss: 0.0074\n","Epoch 9/12\n","92/92 [==============================] - 27s 290ms/step - loss: 8.1929e-04 - val_loss: 0.0018\n","Epoch 10/12\n","92/92 [==============================] - 28s 308ms/step - loss: 3.1160e-04 - val_loss: 0.0177\n","Epoch 11/12\n","92/92 [==============================] - 25s 276ms/step - loss: 5.9725e-04 - val_loss: 0.0119\n","Epoch 12/12\n","92/92 [==============================] - 27s 295ms/step - loss: 4.6180e-04 - val_loss: 0.0040\n","Model: \"sequential_13\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_31 (Conv2D)           (None, 264, 68, 7)        70        \n","_________________________________________________________________\n","max_pooling2d_26 (MaxPooling (None, 88, 22, 7)         0         \n","_________________________________________________________________\n","batch_normalization_7 (Batch (None, 88, 22, 7)         28        \n","_________________________________________________________________\n","conv2d_32 (Conv2D)           (None, 43, 20, 7)         448       \n","_________________________________________________________________\n","max_pooling2d_27 (MaxPooling (None, 14, 6, 7)          0         \n","_________________________________________________________________\n","batch_normalization_8 (Batch (None, 14, 6, 7)          28        \n","_________________________________________________________________\n","conv2d_33 (Conv2D)           (None, 6, 4, 7)           448       \n","_________________________________________________________________\n","max_pooling2d_28 (MaxPooling (None, 2, 1, 7)           0         \n","_________________________________________________________________\n","flatten_13 (Flatten)         (None, 14)                0         \n","_________________________________________________________________\n","dense_13 (Dense)             (None, 1)                 15        \n","=================================================================\n","Total params: 1,037\n","Trainable params: 1,009\n","Non-trainable params: 28\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  SGD\n","max_pool_size :  3\n","learning_rate :  0.0002831804172327656\n","layer_number :  3\n","kernel_size :  3\n","kernel_number :  7\n","batch_normalization :  True\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 34s 368ms/step - loss: 0.0694 - val_loss: 0.1934\n","Epoch 2/12\n","92/92 [==============================] - 24s 262ms/step - loss: 0.0591 - val_loss: 0.2450\n","Epoch 3/12\n","92/92 [==============================] - 24s 266ms/step - loss: 0.0658 - val_loss: 0.1641\n","Epoch 4/12\n","92/92 [==============================] - 27s 298ms/step - loss: 0.0670 - val_loss: 0.1285\n","Epoch 5/12\n","92/92 [==============================] - 27s 288ms/step - loss: 0.0694 - val_loss: 0.0675\n","Epoch 6/12\n","92/92 [==============================] - 26s 286ms/step - loss: 0.0712 - val_loss: 0.1270\n","Epoch 7/12\n","92/92 [==============================] - 26s 284ms/step - loss: 0.0700 - val_loss: 0.1653\n","Epoch 8/12\n","92/92 [==============================] - 28s 302ms/step - loss: 0.0562 - val_loss: 0.1619\n","Epoch 9/12\n","92/92 [==============================] - 26s 278ms/step - loss: 0.0350 - val_loss: 0.0921\n","Epoch 10/12\n","92/92 [==============================] - 26s 286ms/step - loss: 0.0522 - val_loss: 0.0122\n","Epoch 11/12\n","92/92 [==============================] - 26s 284ms/step - loss: 0.0712 - val_loss: 0.0293\n","Epoch 12/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.0933 - val_loss: 0.0430\n","Model: \"sequential_14\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_34 (Conv2D)           (None, 263, 66, 3)        78        \n","_________________________________________________________________\n","max_pooling2d_29 (MaxPooling (None, 65, 16, 3)         0         \n","_________________________________________________________________\n","conv2d_35 (Conv2D)           (None, 31, 12, 3)         228       \n","_________________________________________________________________\n","max_pooling2d_30 (MaxPooling (None, 7, 3, 3)           0         \n","_________________________________________________________________\n","flatten_14 (Flatten)         (None, 63)                0         \n","_________________________________________________________________\n","dense_14 (Dense)             (None, 1)                 64        \n","=================================================================\n","Total params: 370\n","Trainable params: 370\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  2\n","optimizer :  SGD\n","max_pool_size :  4\n","learning_rate :  0.00035656991930916514\n","layer_number :  2\n","kernel_size :  5\n","kernel_number :  3\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 33s 364ms/step - loss: 0.2235 - val_loss: 0.2151\n","Epoch 2/12\n","92/92 [==============================] - 25s 272ms/step - loss: 0.2454 - val_loss: 0.2313\n","Epoch 3/12\n","92/92 [==============================] - 26s 287ms/step - loss: 0.2426 - val_loss: 0.2481\n","Epoch 4/12\n","92/92 [==============================] - 25s 276ms/step - loss: 0.2469 - val_loss: 0.2066\n","Epoch 5/12\n","92/92 [==============================] - 27s 296ms/step - loss: 0.2398 - val_loss: 0.2319\n","Epoch 6/12\n","92/92 [==============================] - 27s 294ms/step - loss: 0.2323 - val_loss: 0.2545\n","Epoch 7/12\n","92/92 [==============================] - 27s 298ms/step - loss: 0.2309 - val_loss: 0.2353\n","Epoch 8/12\n","92/92 [==============================] - 28s 304ms/step - loss: 0.2356 - val_loss: 0.2278\n","Epoch 9/12\n","92/92 [==============================] - 26s 288ms/step - loss: 0.2360 - val_loss: 0.2517\n","Epoch 10/12\n","92/92 [==============================] - 27s 289ms/step - loss: 0.2291 - val_loss: 0.2166\n","Epoch 11/12\n","92/92 [==============================] - 25s 270ms/step - loss: 0.2329 - val_loss: 0.2448\n","Epoch 12/12\n","92/92 [==============================] - 27s 295ms/step - loss: 0.2253 - val_loss: 0.2305\n","Tried to create a MaxPool Layer that is not possible to create, because it would lead to negative dimensions. Creation was skipped\n","Model: \"sequential_15\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_36 (Conv2D)           (None, 527, 67, 5)        85        \n","_________________________________________________________________\n","max_pooling2d_31 (MaxPooling (None, 131, 16, 5)        0         \n","_________________________________________________________________\n","batch_normalization_9 (Batch (None, 131, 16, 5)        20        \n","_________________________________________________________________\n","conv2d_37 (Conv2D)           (None, 128, 13, 5)        405       \n","_________________________________________________________________\n","max_pooling2d_32 (MaxPooling (None, 32, 3, 5)          0         \n","_________________________________________________________________\n","batch_normalization_10 (Batc (None, 32, 3, 5)          20        \n","_________________________________________________________________\n","flatten_15 (Flatten)         (None, 480)               0         \n","_________________________________________________________________\n","dense_15 (Dense)             (None, 1)                 481       \n","=================================================================\n","Total params: 1,011\n","Trainable params: 991\n","Non-trainable params: 20\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  SGD\n","max_pool_size :  4\n","learning_rate :  0.0001064073451061438\n","layer_number :  3\n","kernel_size :  4\n","kernel_number :  5\n","batch_normalization :  True\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 32s 346ms/step - loss: 0.1932 - val_loss: 0.1757\n","Epoch 2/12\n","92/92 [==============================] - 25s 275ms/step - loss: 0.2016 - val_loss: 0.1397\n","Epoch 3/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.2012 - val_loss: 0.1338\n","Epoch 4/12\n","92/92 [==============================] - 27s 293ms/step - loss: 0.1748 - val_loss: 0.1119\n","Epoch 5/12\n","92/92 [==============================] - 25s 269ms/step - loss: 0.1924 - val_loss: 0.0954\n","Epoch 6/12\n","92/92 [==============================] - 26s 287ms/step - loss: 0.1465 - val_loss: 0.0958\n","Epoch 7/12\n","92/92 [==============================] - 27s 289ms/step - loss: 0.1570 - val_loss: 0.1659\n","Epoch 8/12\n","92/92 [==============================] - 28s 299ms/step - loss: 0.1519 - val_loss: 0.1166\n","Epoch 9/12\n","92/92 [==============================] - 27s 297ms/step - loss: 0.1416 - val_loss: 0.0602\n","Epoch 10/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.1902 - val_loss: 0.1808\n","Epoch 11/12\n","92/92 [==============================] - 25s 270ms/step - loss: 0.1942 - val_loss: 0.1467\n","Epoch 12/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.1910 - val_loss: 0.2007\n","Model: \"sequential_16\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_39 (Conv2D)           (None, 523, 63, 6)        390       \n","_________________________________________________________________\n","max_pooling2d_33 (MaxPooling (None, 174, 21, 6)        0         \n","_________________________________________________________________\n","conv2d_40 (Conv2D)           (None, 167, 14, 6)        2310      \n","_________________________________________________________________\n","max_pooling2d_34 (MaxPooling (None, 55, 4, 6)          0         \n","_________________________________________________________________\n","flatten_16 (Flatten)         (None, 1320)              0         \n","_________________________________________________________________\n","dense_16 (Dense)             (None, 1)                 1321      \n","=================================================================\n","Total params: 4,021\n","Trainable params: 4,021\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  Adam\n","max_pool_size :  3\n","learning_rate :  0.0004260549952308603\n","layer_number :  2\n","kernel_size :  8\n","kernel_number :  6\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 32s 346ms/step - loss: 0.0435 - val_loss: 0.0024\n","Epoch 2/12\n","92/92 [==============================] - 27s 291ms/step - loss: 0.0017 - val_loss: 0.0037\n","Epoch 3/12\n","92/92 [==============================] - 25s 271ms/step - loss: 0.0015 - val_loss: 8.3195e-04\n","Epoch 4/12\n","92/92 [==============================] - 26s 286ms/step - loss: 0.0015 - val_loss: 7.1216e-04\n","Epoch 5/12\n","92/92 [==============================] - 26s 284ms/step - loss: 0.0016 - val_loss: 0.0024\n","Epoch 6/12\n","92/92 [==============================] - 27s 288ms/step - loss: 0.0019 - val_loss: 0.0010\n","Epoch 7/12\n","92/92 [==============================] - 25s 277ms/step - loss: 6.5738e-04 - val_loss: 1.9387e-04\n","Epoch 8/12\n","92/92 [==============================] - 26s 282ms/step - loss: 3.7411e-04 - val_loss: 9.3775e-05\n","Epoch 9/12\n","92/92 [==============================] - 25s 277ms/step - loss: 3.3640e-04 - val_loss: 1.5012e-04\n","Epoch 10/12\n","92/92 [==============================] - 26s 288ms/step - loss: 2.8738e-04 - val_loss: 3.5866e-04\n","Epoch 11/12\n","92/92 [==============================] - 26s 281ms/step - loss: 2.8200e-04 - val_loss: 3.4450e-04\n","Epoch 12/12\n","92/92 [==============================] - 30s 321ms/step - loss: 1.8607e-04 - val_loss: 0.0011\n","Model: \"sequential_17\"\n","_________________________________________________________________\n","Layer (type)                 Output Shape              Param #   \n","=================================================================\n","conv2d_41 (Conv2D)           (None, 528, 68, 6)        60        \n","_________________________________________________________________\n","max_pooling2d_35 (MaxPooling (None, 264, 34, 6)        0         \n","_________________________________________________________________\n","conv2d_42 (Conv2D)           (None, 262, 32, 6)        330       \n","_________________________________________________________________\n","max_pooling2d_36 (MaxPooling (None, 131, 16, 6)        0         \n","_________________________________________________________________\n","conv2d_43 (Conv2D)           (None, 129, 14, 6)        330       \n","_________________________________________________________________\n","max_pooling2d_37 (MaxPooling (None, 64, 7, 6)          0         \n","_________________________________________________________________\n","flatten_17 (Flatten)         (None, 2688)              0         \n","_________________________________________________________________\n","dense_17 (Dense)             (None, 1)                 2689      \n","=================================================================\n","Total params: 3,409\n","Trainable params: 3,409\n","Non-trainable params: 0\n","_________________________________________________________________\n","Actual model is using following hyper-parameters:\n","y_stride :  1\n","optimizer :  Adam\n","max_pool_size :  2\n","learning_rate :  0.011420041530456216\n","layer_number :  3\n","kernel_size :  3\n","kernel_number :  6\n","batch_normalization :  False\n","filter_cols :  5\n","batch_size :  8\n","filter_cols_factor :  1\n","filter_rows_factor :  1\n","/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py:49: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence class.\n","  UserWarning('Using a generator with `use_multiprocessing=True`'\n","Epoch 1/12\n","92/92 [==============================] - 32s 347ms/step - loss: 0.0051 - val_loss: 0.0031\n","Epoch 2/12\n","92/92 [==============================] - 27s 293ms/step - loss: 0.0015 - val_loss: 0.0041\n","Epoch 3/12\n","92/92 [==============================] - 26s 285ms/step - loss: 0.0021 - val_loss: 0.0014\n","Epoch 4/12\n","92/92 [==============================] - 25s 276ms/step - loss: 0.0016 - val_loss: 0.0016\n","Epoch 5/12\n","34/92 [==========>...................] - ETA: 15s - loss: 0.0022"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"kOfBHA8FTVdB","colab_type":"code","colab":{}},"source":["# use this code to prevent colab from disconnecting during longer training times in javascript console window\n","function ClickConnect(){\n","    console.log(\"Clicked on connect button\"); \n","    document.querySelector(\"colab-connect-button\").click()\n","}\n","setInterval(ClickConnect,60000)"],"execution_count":0,"outputs":[]}]}